name: 'Run ORT'
description: >
  Run oss-review-toolkit to review Open Source software dependencies.
author: "Sovereign Cloud Stack"
branding:
  icon: "activity"
  color: "green"

outputs:
  analyzer-result:
    description: "output file for the analyze step"
    value: ${{ steps.analyze.outputs.analyzer-result }}
  evaluation-result:
    description: "output file for the evaluate step"
    value: ${{ steps.evaluate.outputs.evaluation-result }}
  results-dir:
    description: "output directory for the report step"
    value: ${{ steps.init.outputs.results-dir }}

inputs:
  ort-version:
    description: "sovereigncloudstack/ort docker hub tag to use."
    required: false
    default: 'main'
  analyze:
    description: >
      Set to `false` to disable the execution of the ORT `analyze`
      ORT Action. Default: `true`.
    required: false
    default: true
  evaluate:
    description: >
      Set to `false` to disable the execution of the ORT `evaluate`
      ORT Action. Default: `true`.
    required: false
    default: true
  report:
    description: >
      Set to `false` to disable the execution of the ORT `report`
      ORT Action. Default: `true`.
    required: false
    default: true
  verbosity:
    description: >
      Verbosity level in ORT to use. Possible values: [
        `warn`, `info`, `performance`, `debug`]. Default to `warn`.
    required: false
    default: 'warn'
  package-curations-dir:
    description: >-
      Specifies path relative to the project directory for the curations
      directory. Used in `analyze` and `evaluate` actions. It's the
      `--package-curations-dir` option for ORT.
    required: false
  rules-file:
    description: >-
      Specifies path relative to the project directory for the rules of the
      `evaluate` action. It's the `--rules-file` option for ORT.
    required: false
  license-classifications-file:
    description: >-
      Specifies path relative to the project directory for the license
      classifications file of the `evaluate` action. It's the
      `--license-classifications-file` option for ORT.
    required: false
  reporters:
    description: >-
      List of reporters to run. Default: Excel,StaticHtml,WebApp
    required: false
    default: Excel,StaticHtml,WebApp
  ort-extra-args:
    description: >-
      List of extra arguments for ORT, for all commands, set before
      the verb (before analyze, evaluate or report).
    required: false
    default: ""
  analyze-extra-args:
    description: List of extra arguments for the `analyze` action.
    required: false
  evaluate-extra-args:
    description: List of extra arguments for the `evaluate` action.
    required: false
  report-extra-args:
    description: List of extra arguments for the `report` action.
    required: false

runs:
  using: "composite"
  steps:
    - name: Initialization
      id: init
      shell: bash
      env:
        VERBOSITY: ${{ inputs.verbosity }}
      run: |
        echo "-----------------------------------------------------------------"
        echo " Initialization step"
        echo "-----------------------------------------------------------------"
        echo " Inputs: "
        echo "    VERBOSITY : '${VERBOSITY}' "
        echo "-----------------------------------------------------------------"

        [ -d ${{ github.workspace }}/ort/ ] || mkdir ${{ github.workspace }}/ort/
        [ -d ${{ github.workspace }}/.ort/ ] || mkdir ${{ github.workspace }}/.ort/
        [ -d ${{ github.workspace }}/.ort/cache ] || mkdir ${{ github.workspace }}/.ort/cache
        [ -d ${{ github.workspace }}/.config/ ] || mkdir ${{ github.workspace }}/.config/
        [ -d ${{ github.workspace }}/.cache/ ] || mkdir ${{ github.workspace }}/.cache/
        [ -d ${{ github.workspace }}/.local/ ] || mkdir ${{ github.workspace }}/.local/
        [ -d ${{ github.workspace }}/.bundle/ ] || mkdir ${{ github.workspace }}/.bundle/
        chmod -R aug+w ${{ github.workspace }}/
        echo "-----------------------------------------------------------------"
        echo " Output directory ${{ github.workspace }}/ort/ contents:"
        echo "-----------------------------------------------------------------"
        ls -lah ${{ github.workspace }}/ort/
        echo "-----------------------------------------------------------------"
        echo "::set-output name=results-dir::ort/"
        echo "-----------------------------------------------------------------"
        echo " Parsing VERBOSITY"
        echo "-----------------------------------------------------------------"
        if [ ${VERBOSITY} = "warn" ]; then
          echo "::set-output name=verbosity::"
          echo " Setting verbosity as warning level"
        elif [[ ${VERBOSITY} == +(info|performance|debug) ]]; then
          echo "::set-output name=verbosity::--${VERBOSITY}"
          echo " Setting verbosity as ${VERBOSITY} level"
        else
          echo "Error: verbosity='${VERBOSITY}' should be one of: warn, debug, info, performance"
          exit 1
        fi
        echo "-----------------------------------------------------------------"

    - name: ORT analyze
      id: analyze
      shell: bash
      env:
        ORT_EXTRA_ARGS: ${{ inputs.ort-extra-args }}
        VERBOSITY: ${{ steps.init.outputs.verbosity }}
        RUN_ANALYZE: ${{ inputs.analyze }}
        ANALYZE_EXTRA_ARGS: ${{ inputs.analyze-extra-args }}
      run: |
        [ "${RUN_ANALYZE}" = "true" ] || \
          { echo "analyze is not true but '${RUN_ANALYZE}' so don't perform this step"; exit 0; }
        export USER_ID=$(id -u ${USER})
        echo "-----------------------------------------------------------------"
        echo " ORT analyze step"
        echo "-----------------------------------------------------------------"
        echo " Inputs: "
        echo "    ORT_EXTRA_ARGS     : '${ORT_EXTRA_ARGS}' "
        echo "    ANALYZE_EXTRA_ARGS : '${ANALYZE_EXTRA_ARGS}' "
        echo "-----------------------------------------------------------------"
        echo " Set X_EXTRA_ARGS from ANALYZE_EXTRA_ARGS"
        echo "-----------------------------------------------------------------"
        [ -z "$ANALYZE_EXTRA_ARGS" ] && \
          X_EXTRA_ARGS="" || \
          X_EXTRA_ARGS="${ANALYZE_EXTRA_ARGS}"
        echo "          X_EXTRA_ARGS: '${X_EXTRA_ARGS}'"
        echo "-----------------------------------------------------------------"
        echo " Running ORT analyze"
        echo "-----------------------------------------------------------------"
        cat << EOF
        docker run \\
          -e ORT_DATA_DIR=/project/.ort/ \\
          -e JAVA_OPTS="--illegal-access=permit" \\
          -e SBT_OPTS="-verbose -debug -Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2" \\
          -v ${{ github.workspace }}/.config:/.config \\
          -v ${{ github.workspace }}/.cache:/.cache \\
          -v ${{ github.workspace }}/.local:/.local \\
          -v ${{ github.workspace }}/.bundle:/.bundle \\
          -v ${{ github.workspace }}:/project \\
          --user ${USER_ID} \\
          ghcr.io/sovereigncloudstack/ort:${{ inputs.ort-version }} \\
          ${ORT_EXTRA_ARGS} \\
          ${VERBOSITY} \\
          analyze \\
          -i /project \\
          -o /project/ort \\
          ${X_EXTRA_ARGS}
        EOF
        docker run \
          -e ORT_DATA_DIR=/project/.ort/ \
          -e JAVA_OPTS="--illegal-access=permit" \
          -e SBT_OPTS="-Dsbt.global.base=.sbt -Dsbt.boot.directory=.sbt -Dsbt.ivy.home=.ivy2" \
          -v ${{ github.workspace }}/.config:/.config \
          -v ${{ github.workspace }}/.cache:/.cache \
          -v ${{ github.workspace }}/.local:/.local \
          -v ${{ github.workspace }}/.bundle:/.bundle \
          -v ${{ github.workspace }}:/project \
          --user ${USER_ID} \
          ghcr.io/sovereigncloudstack/ort:${{ inputs.ort-version }} \
          ${ORT_EXTRA_ARGS} \
          ${VERBOSITY} \
          analyze \
          -i /project \
          -o /project/ort \
          ${X_EXTRA_ARGS}
        echo "-----------------------------------------------------------------"
        echo " Finished!"
        echo "-----------------------------------------------------------------"
        echo " Output directory ${{ github.workspace }}/ort/ contents:"
        echo "-----------------------------------------------------------------"
        ls -lah ${{ github.workspace }}/ort/
        echo "-----------------------------------------------------------------"
        echo "::set-output name=analyzer-result::ort/analyzer-result.yml"

    - name: ORT evaluate
      id: evaluate
      shell: bash
      env:
        ORT_EXTRA_ARGS: ${{ inputs.ort-extra-args }}
        VERBOSITY: ${{ steps.init.outputs.verbosity }}
        RUN_EVALUATE: ${{ inputs.evaluate }}
        PACKAGE_CURATIONS_DIR: ${{ inputs.package-curations-dir }}
        RULES_FILE: ${{ inputs.rules-file }}
        LICENSE_CLASSIFICATIONS_FILE: ${{ inputs.license-classifications-file }}
        EVALUATE_EXTRA_ARGS: ${{ inputs.evaluate-extra-args }}
      run: |
        [ "${RUN_EVALUATE}" = "true" ] || \
          { echo "evaluate is not true but '${RUN_EVALUATE}' so don't perform this step"; exit 0; }
        echo "-----------------------------------------------------------------"
        echo " ORT evaluate step"
        echo "-----------------------------------------------------------------"
        echo " Inputs: "
        echo "    ORT_EXTRA_ARGS               : '${ORT_EXTRA_ARGS}' "
        echo "    PACKAGE_CURATIONS_DIR        : '${PACKAGE_CURATIONS_DIR}' "
        echo "    RULES_FILE                   : '${RULES_FILE}' "
        echo "    LICENSE_CLASSIFICATIONS_FILE : '${LICENSE_CLASSIFICATIONS_FILE}' "
        echo "    EVALUATE_EXTRA_ARGS          : '${EVALUATE_EXTRA_ARGS}' "
        echo "-----------------------------------------------------------------"
        echo " Set X_CURATIONS_DIR from PACKAGE_CURATIONS_DIR"
        echo "-----------------------------------------------------------------"
        [ -z "$PACKAGE_CURATIONS_DIR" ] && \
          X_CURATIONS_DIR="" || \
          X_CURATIONS_DIR="--package-curations-dir /project/${PACKAGE_CURATIONS_DIR}"
        echo "          X_CURATIONS_DIR: '${X_CURATIONS_DIR}'"
        echo " Set X_RULES_FILE from RULES_FILE"
        echo "-----------------------------------------------------------------"
        [ -z "$RULES_FILE" ] && \
          X_RULES_FILE="" || \
          X_RULES_FILE="--rules-file /project/${RULES_FILE}"
        echo "          X_RULES_FILE: '${X_RULES_FILE}'"
        echo "-----------------------------------------------------------------"
        echo " Set X_LICENSE_CLASS from LICENSE_CLASSIFICATIONS_FILE"
        echo "-----------------------------------------------------------------"
        [ -z "$LICENSE_CLASSIFICATIONS_FILE" ] && \
          X_LICENSE_CLASS="" || \
          X_LICENSE_CLASS="--license-classifications-file /project/${LICENSE_CLASSIFICATIONS_FILE}"
        echo "          X_LICENSE_CLASS: '${X_LICENSE_CLASS}'"
        echo "-----------------------------------------------------------------"
        echo " Set X_EXTRA_ARGS"
        echo "-----------------------------------------------------------------"
        [ -z "$EVALUATE_EXTRA_ARGS" ] && \
          X_EXTRA_ARGS="" || \
          X_EXTRA_ARGS="${EVALUATE_EXTRA_ARGS}"
        echo "          X_EXTRA_ARGS: '${X_EXTRA_ARGS}'"
        echo "-----------------------------------------------------------------"
        docker run \
          -e ORT_DATA_DIR=/project/.ort/ \
          -v ${{ github.workspace }}:/project \
          --user 10001 \
          ghcr.io/sovereigncloudstack/ort:${{ inputs.ort-version }} \
          ${ORT_EXTRA_ARGS} \
          ${VERBOSITY} \
          evaluate \
          -i /project/ort/analyzer-result.yml \
          -o /project/ort \
          ${X_CURATIONS_DIR} \
          ${X_RULES_FILE} \
          ${X_LICENSE_CLASS} \
          ${X_EXTRA_ARGS}
        echo "-----------------------------------------------------------------"
        echo " Finished!"
        echo "-----------------------------------------------------------------"
        echo " Output directory ${{ github.workspace }}/ort/ contents:"
        echo "-----------------------------------------------------------------"
        ls -lah ${{ github.workspace }}/ort/
        echo "-----------------------------------------------------------------"
        echo "::set-output name=evaluation-result::ort/evaluation-result.yml"

    - name: ORT report
      id: report
      shell: bash
      env:
        ORT_EXTRA_ARGS: ${{ inputs.ort-extra-args }}
        VERBOSITY: ${{ steps.init.outputs.verbosity }}
        RUN_REPORT: ${{ inputs.report }}
        REPORTERS: ${{ inputs.reporters }}
        REPORT_EXTRA_ARGS: ${{ inputs.report-extra-args }}
      run: |
        [ "${RUN_REPORT}" = "true" ] || \
          { echo "report is not true but '${RUN_REPORT}' so don't perform this step"; exit 0; }
        echo "-----------------------------------------------------------------"
        echo " ORT report step"
        echo "-----------------------------------------------------------------"
        echo " Inputs: "
        echo "    ORT_EXTRA_ARGS    : '${ORT_EXTRA_ARGS}' "
        echo "    REPORTERS         : '${REPORTERS}' "
        echo "    REPORT_EXTRA_ARGS : '${REPORT_EXTRA_ARGS}' "
        echo "-----------------------------------------------------------------"
        echo " Set X_REPORTERS from REPORTERS"
        echo "-----------------------------------------------------------------"
        [ -z "$REPORTERS" ] && \
          X_REPORTERS="" || \
          X_REPORTERS="${REPORTERS}"
        echo "          X_REPORTERS: '${X_REPORTERS}'"
        echo "-----------------------------------------------------------------"
        echo " Set X_EXTRA_ARGS from REPORT_EXTRA_ARGS"
        echo "-----------------------------------------------------------------"
        [ -z "$REPORT_EXTRA_ARGS" ] && \
          X_EXTRA_ARGS="" || \
          X_EXTRA_ARGS="${REPORT_EXTRA_ARGS}"
        echo "          X_EXTRA_ARGS: '${X_EXTRA_ARGS}'"
        echo "-----------------------------------------------------------------"
        echo " Running ORT report"
        echo "-----------------------------------------------------------------"
        echo "command: 'docker run -e ORT_DATA_DIR=/project/.ort/ -v ${{ github.workspace }}:/project --user 10001  ghcr.io/sovereigncloudstack/ort:${{ inputs.ort-version }} --info report  -i /project/ort/evaluation-result.yml  -o /project/ort -f ${X_REPORTERS} ${X_EXTRA_ARGS}'"
        docker run \
          -e ORT_DATA_DIR=/project/.ort/ \
          -v ${{ github.workspace }}:/project \
          --user 10001 \
          ghcr.io/sovereigncloudstack/ort:${{ inputs.ort-version }} \
          ${ORT_EXTRA_ARGS} \
          ${VERBOSITY} \
          report \
          -i /project/ort/evaluation-result.yml \
          -o /project/ort \
          -f ${X_REPORTERS} \
          ${X_EXTRA_ARGS}
        echo "-----------------------------------------------------------------"
        echo " Finished!"
        echo "-----------------------------------------------------------------"
        echo " Output directory ${{ github.workspace }}/ort/ contents:"
        echo "-----------------------------------------------------------------"
        ls -lah ${{ github.workspace }}/ort/
        echo "-----------------------------------------------------------------"
